application: 
version: 1
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
- url: /_ah/channel/connected/
  script: _go_app

- url: /_ah/channel/disconnected/
  script: _go_app

- url: /.*
  script: _go_app

